security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN:  ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider:   fos_userbundle
                check_path: /login_check
                login_path: /login
                default_target_path: /schedule
           #     use_referer:    true                
            logout:
                path:          /logout
                target:        /                
            anonymous:    true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login$
            security: false

    access_control:
        - { path: ^/schedule.*, roles: ROLE_USER}
        - { path: ^/schedule/jobs.*, roles: ROLE_USER}
        - { path: ^/schedule/proyects.*, roles: ROLE_USER}
        - { path: ^/schedule/user.*, roles: ROLE_ADMIN}
        - { path: ^/schedule/activities.*, roles: ROLE_ADMIN}